// <auto-generated />
using System;
using Jrg.SisMed.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jrg.SisMed.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Cidade");

                    b.Property<string>("Complement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Complemento do endereço");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Data de criação do registro");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int")
                        .HasComment("ID da pessoa que criou o registro");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número do endereço");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("Estado/UF (sigla)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nome da rua/logradouro");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasComment("ID da pessoa que atualizou o registro");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasComment("CEP (apenas números)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Addresses_CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("ZipCode")
                        .HasDatabaseName("IX_Addresses_ZipCode");

                    b.HasIndex("City", "State")
                        .HasDatabaseName("IX_Addresses_City_State");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasComment("Cnpj da organização (apenas números)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Data de criação do registro");

                    b.Property<string>("NameFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Nome fantasia da organização (nome comercial)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Razão social da organização (nome jurídico)");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasComment("Estado da organização: 1=Active, 2=Inactive, 3=Suspended");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("IX_Organizations_CNPJ");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Organizations_CreatedAt");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Organizations_State");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.OrganizationPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Data de criação do registro");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int")
                        .HasComment("ID da pessoa que criou o registro");

                    b.Property<bool>("IsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica se é o telefone principal");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasComment("ID da organização");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int")
                        .HasComment("ID do telefone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasComment("ID da pessoa que atualizou o registro");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsPrincipal")
                        .HasDatabaseName("IX_OrganizationPhones_IsPrincipal");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_OrganizationPhones_OrganizationId");

                    b.HasIndex("PhoneId")
                        .HasDatabaseName("IX_OrganizationPhones_PhoneId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("OrganizationId", "PhoneId")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationPhones_OrganizationId_PhoneId");

                    b.ToTable("OrganizationPhones", (string)null);
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Data de criação do registro");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int")
                        .HasComment("ID da pessoa que criou o registro");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("Código DDD (código de área)");

                    b.Property<string>("Ddi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasComment("Código DDI (código internacional do país)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasComment("Número do telefone (8 ou 9 dígitos)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasComment("ID da pessoa que atualizou o registro");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Phones_CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Ddi", "Ddd", "Number")
                        .IsUnique()
                        .HasDatabaseName("IX_Phones_Full_Number");

                    b.ToTable("Phones", (string)null);
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasComment("Data de nascimento");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasComment("CPF do profissional (apenas números)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Data de criação do registro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("E-mail do profissional");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasComment("Gênero: 0=None, 1=Male, 2=Female, 3=Other");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Nome completo do Professional");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Hash da senha (PBKDF2)");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("RG do profissional");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasComment("Estado do profissional: 1=Active, 2=Inactive");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Professional_CPF");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Professional_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Professional_Email");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Professional_Name");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Professional_State");

                    b.ToTable("Professionals", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.ProfessionalAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasComment("ID do endereço");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Data de criação do registro");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int")
                        .HasComment("ID do profissional que criou o registro");

                    b.Property<bool>("IsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica se é o endereço principal");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int")
                        .HasComment("ID do profissional");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasComment("ID do profissional que atualizou o registro");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("IX_ProfessionalAddresses_AddressId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsPrincipal")
                        .HasDatabaseName("IX_ProfessionalAddresses_IsPrincipal");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("IX_ProfessionalAddresses_ProfessionalId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("ProfessionalId", "AddressId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProfessionalAddresses_ProfessionalId_AddressId");

                    b.ToTable("ProfessionalAddresses", (string)null);
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.ProfessionalPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Data de criação do registro");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int")
                        .HasComment("ID do profissional que criou o registro");

                    b.Property<bool>("IsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica se é o telefone principal");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int")
                        .HasComment("ID do telefone");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int")
                        .HasComment("ID o profissional");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasComment("ID do profissional que atualizou o registro");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsPrincipal")
                        .HasDatabaseName("IX_ProfessionalPhones_IsPrincipal");

                    b.HasIndex("PhoneId")
                        .HasDatabaseName("IX_ProfessionalPhones_PhoneId");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("IX_ProfessionalPhones_ProfessionalId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("ProfessionalId", "PhoneId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProfessionalPhones_ProfessionalId_PhoneId");

                    b.ToTable("ProfessionalPhones", (string)null);
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Nutritionist", b =>
                {
                    b.HasBaseType("Jrg.SisMed.Domain.Entities.Professional");

                    b.Property<string>("Crn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número do registro no Conselho Regional de Nutricionistas (CRN)");

                    b.HasIndex("Crn")
                        .IsUnique()
                        .HasDatabaseName("IX_Nutritionists_Crn")
                        .HasFilter("[Crn] IS NOT NULL");

                    b.ToTable("Nutritionists", (string)null);
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Psychologist", b =>
                {
                    b.HasBaseType("Jrg.SisMed.Domain.Entities.Professional");

                    b.Property<string>("Crp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número do registro no Conselho Regional de Psicologia (CRP)");

                    b.HasIndex("Crp")
                        .IsUnique()
                        .HasDatabaseName("IX_Psychologists_Crp")
                        .HasFilter("[Crp] IS NOT NULL");

                    b.ToTable("Psychologists", (string)null);
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Address", b =>
                {
                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.OrganizationPhone", b =>
                {
                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jrg.SisMed.Domain.Entities.Organization", "Organization")
                        .WithMany("Phones")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jrg.SisMed.Domain.Entities.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Organization");

                    b.Navigation("Phone");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Phone", b =>
                {
                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.ProfessionalAddress", b =>
                {
                    b.HasOne("Jrg.SisMed.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "Professional")
                        .WithMany("Addresses")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("CreatedBy");

                    b.Navigation("Professional");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.ProfessionalPhone", b =>
                {
                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jrg.SisMed.Domain.Entities.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "Professional")
                        .WithMany("Phones")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Phone");

                    b.Navigation("Professional");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Nutritionist", b =>
                {
                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", null)
                        .WithOne()
                        .HasForeignKey("Jrg.SisMed.Domain.Entities.Nutritionist", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Psychologist", b =>
                {
                    b.HasOne("Jrg.SisMed.Domain.Entities.Professional", null)
                        .WithOne()
                        .HasForeignKey("Jrg.SisMed.Domain.Entities.Psychologist", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Jrg.SisMed.Domain.Entities.Professional", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
